title = 'COMP 741/841 Practical Aritificial Intelligence'
theme = "relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = [ "relearn-dark", "relearn-light" ]